workflowVersion: 1.0.0
speakeasyVersion: 1.385.0
sources:
    clerk-openapi:
        inputs:
            - location: openapi.yaml
        overlays:
            - location: ./fixes.yaml
            - location: ./examples.yaml
        registry:
            location: registry.speakeasyapi.dev/clerk/clerk/clerk-openapi
targets:
    clerk-sdk-python:
        target: python
        source: clerk-openapi
        output: .
        publish:
            pypi:
                token: $pypi_token
